# Generated by Django 5.0.4 on 2024-04-21 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='kb.report'),
        ),
        migrations.CreateModel(
            name='Satrlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('ulchov_birligi', models.CharField(max_length=100)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='kb.period')),
            ],
        ),
    ]
