# Generated by Django 5.0.4 on 2024-04-21 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hisobotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('izoh', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Xat_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Muddati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('izoh', models.TextField()),
                ('hisobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jarima.hisobotlar')),
            ],
        ),
        migrations.CreateModel(
            name='Baza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpo', models.CharField(max_length=8)),
                ('inn', models.CharField(max_length=9)),
                ('nomi', models.CharField(max_length=400)),
                ('soato4', models.CharField(blank=True, max_length=4, null=True)),
                ('soato7', models.CharField(max_length=7)),
                ('aniqlangan_sanasi', models.DateField()),
                ('sababi', models.CharField(max_length=400)),
                ('xat_sanasi', models.DateField()),
                ('chiqib_ketgan', models.BooleanField(default=False)),
                ('izoh', models.TextField()),
                ('notijorat', models.BooleanField(default=False)),
                ('sudga_chiqarilgan', models.BooleanField(default=False)),
                ('tugatilgan', models.BooleanField(default=False)),
                ('dalolatnoma', models.BooleanField(default=False)),
                ('faoliyatsiz', models.BooleanField(default=False)),
                ('huquqbuzarlik_soni', models.IntegerField(default=0)),
                ('hisobot_nomi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jarima.hisobotlar')),
                ('topshirish_muddati', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jarima.muddati')),
                ('xat_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jarima.xat_turi')),
            ],
        ),
    ]
