# Generated by Django 5.0.4 on 2024-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='soato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
