# Generated by Django 5.0.4 on 2024-04-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarima', '0002_baza_soato'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
