# Generated by Django 5.0.4 on 2024-04-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarima', '0004_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='innx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jarima.baza'),
        ),
    ]
