# Generated by Django 5.0.4 on 2024-04-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarima', '0005_alter_uploadedfile_innx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baza',
            name='file',
        ),
        migrations.AddField(
            model_name='baza',
            name='yopilgan',
            field=models.BooleanField(default=False),
        ),
    ]
