# Generated by Django 5.0.4 on 2024-04-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarima', '0006_remove_baza_file_baza_yopilgan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza',
            name='yopilgan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
